version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose the port
    environment:
      MONGO_INITDB_ROOT_USERNAME: [USER]  # Username root
      MONGO_INITDB_ROOT_PASSWORD: [PASSWORD]  # Password example
    volumes:
      - mongo-data:/data/db  # Mount the volume

  nestjs:
    image: node:18
    container_name: nestjs
    ports:
      - "3000:3000"  # Expose the port 3000
    volumes:
      - ../:/app  # Mount the project directory
      - /app/node_modules  # Prevent local node_modules from being used because some modules are not compatible
                          # with the container and need to be reinstalled
    working_dir: /app
    command: >
      sh -c "
      npm install &&
      npm run start:dev
      "
    depends_on:
      - mongodb  # Depend on the mongodb service

volumes:
  mongo-data:
    driver: local